// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC19faG0167cCYqOJuB3rN0oGD3GW8MrbM',
    appId: '1:675112259093:web:6c3a9f029acfb83caf081c',
    messagingSenderId: '675112259093',
    projectId: 'mnceshisanyama',
    authDomain: 'mnceshisanyama.firebaseapp.com',
    databaseURL: 'https://mnceshisanyama-default-rtdb.firebaseio.com',
    storageBucket: 'mnceshisanyama.firebasestorage.app',
    measurementId: 'G-C4SST0HD6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbhUIQcMt6gACwEWdyGpV-Sxy7Vjh13l8',
    appId: '1:675112259093:android:6f7b0f1ea126b780af081c',
    messagingSenderId: '675112259093',
    projectId: 'mnceshisanyama',
    databaseURL: 'https://mnceshisanyama-default-rtdb.firebaseio.com',
    storageBucket: 'mnceshisanyama.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc_4qrxPDpWATmCXnvORoakNk46CpnDU0',
    appId: '1:675112259093:ios:78d497499ad6666caf081c',
    messagingSenderId: '675112259093',
    projectId: 'mnceshisanyama',
    databaseURL: 'https://mnceshisanyama-default-rtdb.firebaseio.com',
    storageBucket: 'mnceshisanyama.firebasestorage.app',
    iosBundleId: 'com.example.mnceShisanyama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc_4qrxPDpWATmCXnvORoakNk46CpnDU0',
    appId: '1:675112259093:ios:78d497499ad6666caf081c',
    messagingSenderId: '675112259093',
    projectId: 'mnceshisanyama',
    databaseURL: 'https://mnceshisanyama-default-rtdb.firebaseio.com',
    storageBucket: 'mnceshisanyama.firebasestorage.app',
    iosBundleId: 'com.example.mnceShisanyama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC19faG0167cCYqOJuB3rN0oGD3GW8MrbM',
    appId: '1:675112259093:web:4ffe7b0f1eef4925af081c',
    messagingSenderId: '675112259093',
    projectId: 'mnceshisanyama',
    authDomain: 'mnceshisanyama.firebaseapp.com',
    databaseURL: 'https://mnceshisanyama-default-rtdb.firebaseio.com',
    storageBucket: 'mnceshisanyama.firebasestorage.app',
    measurementId: 'G-DHGJ3YX2X0',
  );
}
